### ISSUE TITLE
Null literals in CSVs aren't handled properly

### ISSUE THREAD

**Issue by prasoon2211** [pretzelai/pretzelai#22]
If in a CSV, there are values that are literally the string "null", currently, we make the assumption that the CSV has generated incorrectly and that these values should have been empty (i.e. no text between the commas)

We read these values currently as null or missing values. But there can be cases where the null literal should be parsed and stored as the string "null". Fix this.

**Comment by JakeRoggenbuck** [comment]
Could I fix this one?

It looks like this line needs to be changed.
https://github.com/pretzelai/pretzelai/blob/b72e150992769e67264fd096a04712a1f5474055/src/components/Upload.tsx#L124

Remove `&& cell !== "null"` to become 
```js
cell !== null && cell !== undefined && !cellIsNan
```

**Comment by ramonverse** [comment]
@JakeRoggenbuck go for it. If you use some example csv to test upload it here too so I can have a look thanks!

**Comment by JakeRoggenbuck** [comment]
Here are two test files.
[test_nulls.csv](https://github.com/pretzelai/pretzelai/files/14733888/test_nulls.csv)
[test_nulls_2.csv](https://github.com/pretzelai/pretzelai/files/14733886/test_nulls_2.csv)

**Comment by ramonverse** [comment]
Fixed in #47
