### ISSUE TITLE
Add support for Parquet and Arrow files

### ISSUE THREAD

**Issue by prasoon2211** [pretzelai/pretzelai#30]

**Comment by MikeBeller** [comment]
correct title to 'Parquet' ?

**Comment by Saketram7575** [comment]
Help

**Comment by ramonverse** [comment]
@Saketram7575 what is your priority? Parquet, Arrow or both? Thanks!

**Comment by dkbalan** [comment]
Would be great to see both but Parquet to begin with if possible. This tool is really good.

**Comment by dkbalan** [comment]
Happy to open a separate issue or connect on another thread as we have tried treading 65 million records via parquet and duckdb wasm and it works fine. 100 million and above will start slowing things down.
