### ISSUE TITLE
Install procedure?

### ISSUE THREAD

**Issue by tophee** [pretzelai/pretzelai#85]
The install procedure doesn't work for me on macOS. I installed (updated) pip with conda and then:

````
(pretzel) % pip install pretzelai
Collecting pretzelai
  Using cached pretzelai-0.2.2-py3-none-any.whl.metadata (4.6 kB)
Using cached pretzelai-0.2.2-py3-none-any.whl (4.6 MB)
Installing collected packages: pretzelai
Successfully installed pretzelai-0.2.2
(pretzel)  % pretzel lab
zsh: command not found: pretzel
(pretzel)  %
````

Edit: also the "Bleeding Edge" installation fails (`error: metadata-generation-failed`)

```
      subprocess.CalledProcessError: Command '['/opt/homebrew/bin/node', 'yarn.js', 'run', 'build:prod:minimize']' returned non-zero exit status 1.

```

**Comment by prasoon2211** [comment]
Hey @tophee - I've just been testing the release today. Apologies for the errors - it seems there was an old package set as the default release on PyPI. I've just released v4.2.0 and tested it on conda - everything is working. 

Please `pip install pretzelai` again and let me know if it does't work. See the release [on PyPI here](https://pypi.org/project/pretzelai/)

---

I've also update the readme with more info so feel free to take a look! Happy to get any feedback either on GitHub or on our email (founders@withpretzel.com)

**Comment by tophee** [comment]
Oh, wow! That fixed it.  I can access the web-UI!  Thanks!

I expected to see my existing jupyter notebooks in the file tree, though, but I probably misunderstood that, so I will figure out how to get them in there. As a beginner, it is not clear to me where I am (in the file tree that s shown on the left and when I click File -> open from path, the expected path is relative the current directory, which I don't know where it is...

I will probably figure it out once I take a close look, but I thought I'd provide you this first first impression of an unexperienced user right away.

**Comment by prasoon2211** [comment]
Thanks for trying out Pretzel @tophee ! Looking forward to your feedback :) Happy to do a quick 5-10 min call to help you get set up!

As for the file tree and your notebooks - the folder where you run `pretzel lab` is the folder you should be able to see in the left sidebar. For eg, I'm launching `pretzel lab` in a folder called `testdir`
<img width="868" alt="image" src="https://github.com/pretzelai/pretzelai/assets/2565248/bf639105-c14d-4d23-b5b3-a5b7896ff236">

Then, when I go to the browser, I see `testdir` in the left sidebar. You can verify the directory by running `!pwd` in a jupyter cell.
![image](https://github.com/pretzelai/pretzelai/assets/2565248/a4050b75-38e6-4623-80e9-183807360758)
