### ISSUE TITLE
Which GPT model?

### ISSUE THREAD

**Issue by tophee** [pretzelai/pretzelai#86]
If I read my OpenAI usage stats correctly, pretzel uses gpt 3.5 exclusively. Is this correct? 

While I cant complain about the results so far, I have long stopped using 3.5 for coding (it may be cheaper but has sometimes cost me hours of debugging that could have been avoided with a better model). But since pretzel works fine so far, I may just have been bad at prompting. Then again the code I tested so far was not particularly sophisticated.

So, I'm wondering whether pretzel dynamically chooses gpt-3.5 or gpt-4o based on some assessment of complexity of the prompt or whether 3.5 is hard coded. In any case, I suppose a setting to allow the user to choose the model is part of the road map?

Edit: I now realize that the API key I use for pretzel has _never_ been used (according to https://platform.openai.com/api-keys), so I'm puzzled where the magic comes from. Or are the OpenAI stats 10+hours behind?

**Comment by prasoon2211** [comment]
Hey - we're using GPT-4o for all coding tasks. Please see the [configuration section](https://github.com/pretzelai/pretzelai?tab=readme-ov-file#configuration) of the readme.

Long story short - out of the box, we use our own little wrapper over OpenAI models to both calculate embeddings and for completion. A lot of people still don't have API keys or don't know how to get them so we made this to make trying out Pretzel's AI features easy.

You can switch to using you Open AI API key in the settings. See the configuration section about instructions.

**Comment by prasoon2211** [comment]
And yes, lots more coming wrt to model configuration including allowing non-openai models, local models via Ollama etc.

**Comment by tophee** [comment]
OK, thanks for clarifying. Entering my OpenAI API key was the first thing I did, but I see now that I didn't switch to the OpenAI server. It didn't occur to me that there would be any other way than my own API key, but I appreciate the convenience via your server. I now see that it says so in the config section. Dunno how I missed it. It doesn't state the model, though. Good to know that we're using 4o. That would also have been my manual choice.
