### ISSUE TITLE
Irrelevant code from previous cells is added to the correct answer

### ISSUE THREAD

**Issue by tophee** [pretzelai/pretzelai#88]
Upon further testing, I find that I am rather frequently getting hallucinations (?) where some irrelevant code from a previous cell is appended to the present cell. 

This tells me that at least some of the previous cells are being sent as context. Assuming that those cells are selected via embeddings, I would say that this doesn't work so well. But I'm not sure whether the problem is that the wrong cells are selected as context (probably not, because the actual task is coded correctly) or whether some selected context triggers some kind of hallucination, perhaps because it is not used in the actual answer, so it is simply appended to the correct answer.

**Comment by prasoon2211** [comment]
Yes, we send some matching cells with the prompt (see also my reply on #87 ) 

This is interesting - I hadn't seen this happen in my testing so far but let me tweak some parameters so it's not matching as many irrelevant results. I'll also tweak the prompt a bit so the result is only relevant code

**Comment by prasoon2211** [comment]
Hey, please see my [comment from issue 89](https://github.com/pretzelai/pretzelai/issues/89#issuecomment-2126433552) - we've made lots of changes so this should be mostly fixed. Will be releasing a new release later today but as mentioned in the comment, you can try the wheel linked there! 

Closing this ticket for now.
