### ISSUE TITLE
Don't remove  comments from my code

### ISSUE THREAD

**Issue by tophee** [pretzelai/pretzelai#89]
I noticed that the AI keeps removing commented lines from my code when it produces its response. Adding "Do not remove any comments from the code" seems to work sometimes but not always.

I suspect that this might be the root cause for that behaviour:

https://github.com/pretzelai/pretzelai/blob/72d10e309b5898ee782845d8e70f57789bdf7fdb/packages/pretzelai-extension/src/prompt.ts#L79

Perhaps changing this to `Based on the above, return ONLY executable python code, no backticks. Keep any comments from the existing code;` could resolve this?

**Comment by prasoon2211** [comment]
Thanks for brining this up @tophee ! We've made some major changes to prompts (including for comments) as well as the context being sent (list of imports, variables in memory) and I think the code generation is way better now. 

We're going to do a release later today on PyPI after some testing but until then, if you like, you can download the wheel file (in case you're not aware, wheels are how python packages are created) from GitHub [here](https://github.com/pretzelai/pretzelai/releases/tag/v4.2.0#:~:text=pretzelai%2D4.2.1%2Dpy3%2Dnone%2Dany.whl)

Once you have the downloaded the wheel file, you simply run `pip install <wheel-file>` to get the latest release :) Looking forward to your feedback!

**Comment by tophee** [comment]
Thanks for the the new version. I installed it with `pip install --upgrade pretzelai` but comments are still being removed. Not all of them, but enough for me to use copy - reject - paste - edit  rather than just accept.

**Comment by prasoon2211** [comment]
Hmm interesting. If you wouldn't mind sharing an example, that would be extremely helpful!

**Comment by tophee** [comment]
@prasoon2211 After using pretzel ai for another couple of dsys, I can say that it still more or less consistently removes comments so that I can rarely accept the proposed code. 

It also sometimes makes changes in the actual code that are unrelated to the query. (apparently mirroring some conventions it was trained on).
